### ISSUE TITLE
bad redirect url

### ISSUE THREAD

**Issue by LGD-Fr** [rezometz/django-paiji2-shoutbox#2]
When you are on the "edit" view of a message you wrote, you can delete the message you are still editing by clicking on a "delete" link that is shown on the left/right block (on paiji2).
If then you confirm you want to delete this message, you are redirected to the old "edit" url of the deleted message… 404 error :-(

**Comment by gpichot** [comment]
From which template is it?

**Comment by LGD-Fr** [comment]
"edit" view : message/form.html
"block" : bulletin_board_short.html
"delete" view : note_confirm_delete.html (line 16)
indeed the "next" POST data is META.HTTP_REFERER (the former "edit" url of the deleted message)

**Comment by gpichot** [comment]
Okay, I see, so it is related to the way that we are managing success_url in case of deletion...

Nice catch! ;p

**Comment by LGD-Fr** [comment]
corrected with SuccessUrlMixin from paiji2_utils
